baseURL: "https://casterr.sbond.co/"
languageCode: "en-us"
title: "Casterr"
enableRobotsTXT: false

Params:
  github: "https://github.com/sbondCo/Casterr"
  features:
    - name: "Recordings Browser"
      icon: "movie.svg"
      desc: "Rich list of your past recordings for your to browse.
        Gives you useful information about the video, such as it's name,
        length, size and FPS along with a thumbnail."
    - name: "Video Clipper"
      icon: "trim.svg"
      desc: "Simple video editor that gives you fine control over sharing 
      exactly what you want to, seamlessly clip parts of your video into a 
      new one. Doubles as a great place for you to watch your videos."
    - name: "Settings"
      icon: "settings.svg"
      desc: "Easily configure your recording and app settings. Casterr aims
        for full customizability in an accessible way. Settings are stored in
        JSON files, which makes backing up and restoring them easy."
    - name: "Open Source"
      icon: "open-lock.svg"
      desc: "Casterr is fully open source and free. It's source code is easily 
        accessible to anyone and modification is encouraged! Head over to the 
        repo to contribute yourself."
    - name: "Cross Platform"
      icon: "cross-platform.svg"
      desc: "Developed for Windows and Linux machines, unfortunately we don't
        currently support OSX though, but that can change through community
        engagement on the matter."
    - name: "Easy & Simple"
      icon: "send.svg"
      desc: "Anyone can use Casterr, it was built with usability and 
        ease-of-access in mind. Everything that can be, is done automatically
        out of sight, which takes all the worry away."
